<?php
$categories = $this->getCategoryCollection();
$categoryHelper = $this->getCategoryHelper();
$canshowImg = $this->canShowImage();
$title = $block->getTitle() ? __($block->getTitle()) : 'Categories';
?>
<?php if ($title):?>
<div class="block-title">
	<strong><?php /* @escapeNotVerified */ echo $title; ?></strong>
</div>
<?php endif ?>
<div class="block-content catalog-category">
	<?php
	//echo get_class($categories);
	foreach($categories as $category):
	    if (!$category->getIsActive()) {
	        continue;
	    } ?>
	    <div class="category category-<?php echo $category->getName(); ?>">
	    	<a href="<?php echo $categoryHelper->getCategoryUrl($category) ?>">
	    		<?php if($canshowImg && $category->getImageUrl()):?>
	    		<figure>
	    			<img src="<?= $category->getImageUrl(); ?>" alt="" width="<?=$this->getImagewidth();?>" height="<?=$this->getImageheight()?>"/>
	    			<figcaption>
		    			<span class="cat-title"><?php echo $category->getName(); ?></span>
	    			</figcaption>
	    		</figure>
	    		<?php else:?>
	    		<span class="cat-title"><?php echo $category->getName(); ?></span>
	    		<?php endif;?>
	    	</a>
	    </div>
	<?php endforeach; ?>
</div>